#pragma config(Sensor, S1,     Luz,                 sensorLightActive)
#pragma config(Sensor, S2,     Proximidad,          sensorSONAR)
#pragma config(Sensor, S3,     Contacto,            sensorTouch)
#pragma config(Motor,  motorA,          ,              tmotorNormal, PIDControl, )
#pragma config(Motor,  motorB,          ,              tmotorNormal, PIDControl, )
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// Constantes
const tSensors sensorLuz = (tSensors) S1; //sensor Luz
const tSensors sensorProximidad = (tSensors) S2; //sensor Proximidad

// Cabecera de Funciones
void mover();
void sacaBola();
void permanecerDentro();
void rastreador();

//------------------------------------------------------
// Funciones
//------------------------------------------------------
// Mover el robot
void mover(int speedA, int speedB){
	motor[motorA]=speedA;
	motor[motorB]=speedB;
}

// Funcion para permanecer dentro del circuito
void permanecerDentro(){
	ClearTimer(T1);
	while(time1[T1]<100){
		mover(0,0);
	}
	ClearTimer(T1);
	while(time1[T1]<2000){
		mover(-85,-85);
	}
	ClearTimer(T1); // Giramos y buscamos bola
	while(SensorValue(sensorLuz)<=50 && time1[T1]<1800){
		mover(40,-40);
		while(SensorValue(sensorProximidad)<50){ sacaBola(); }
	}
	ClearTimer(T1); // Avanzamos y buscamos bola
	while(SensorValue(sensorLuz)<=50 && time1[T1]<1000){
			mover(90,90);
			while(SensorValue(sensorProximidad)<50){ sacaBola(); }
	}
}


// Funcion para tirar una bola fuera del circuito
void sacaBola(){
	while(SensorValue(sensorLuz)<=50){
		mover(90,90);
	}
	if(SensorValue(sensorLuz)>50){ permanecerDentro(); }
}


// Funcion para buscar bolas
void rastreador(){
	while(true){
		while(SensorValue(sensorLuz)<=50){
			while(SensorValue(sensorProximidad)<50){
				sacaBola();
			}
			ClearTimer(T1); // Giramos y buscamos bola
			while(SensorValue(sensorLuz)<=50 && time1[T1]<2700){
					mover(40,-40);
					while(SensorValue(sensorProximidad)<50){ sacaBola(); }
			}
			ClearTimer(T1); // Vamos hacia delante y buscando bola
			while(SensorValue(sensorLuz)<=50 && time1[T1]<1300){
					mover(90,90);
					while(SensorValue(sensorProximidad)<50){ sacaBola(); }
			}
		}
	    permanecerDentro();
	}
}


//------------------------------------------------------
// Tarea Principal
//------------------------------------------------------
task main(){
	mover(90,90);
	rastreador();
}








